services:
  # app:
  #   build:
  #     context: .
  #   image: nextjs-dev
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  db:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_PASSWORD: nopxa6-huzdaD-giphef
    ports:
      - "5432:5432"